var clientsKey="clickc_clients";var statsKey="retro_stats";var themeKey="retro_theme";var state={client:null,slug:null,visitorName:"",visitorCompany:""};var confettiFired=false;
function applyTheme(t){var root=document.body;root.classList.remove("theme-light","theme-dark");root.classList.add(t==="dark"?"theme-dark":"theme-light");localStorage.setItem(themeKey,t)}
function setToggleIcon(el,t){if(!el)return;el.textContent=t==="dark"?"🌙":"☀️"}
function getClients(){var raw=localStorage.getItem(clientsKey);return raw?JSON.parse(raw):[]}
function getClientBySlug(slug){var list=getClients();for(var i=0;i<list.length;i++){if(list[i].slug===slug)return list[i]}return null}
function setBrand(c){document.documentElement.style.setProperty("--brand",c)}
function setLogo(src){var el=document.getElementById("brandLogo");if(src){el.src=src;el.style.display="block"}else{el.style.display="none"}}
function getSlug(){var h=location.hash.replace(/^#\/?/i,"");if(h)return h;var p=location.pathname.replace(/\/?index\.html$/i,"").replace(/^\/+/,"");if(p){var seg=p.split("/")[0];if(seg)return seg}return "demo"}
function show(id){document.getElementById("landing").classList.add("hidden");document.getElementById("loading").classList.add("hidden");document.getElementById("retrospective").classList.add("hidden");document.getElementById(id).classList.remove("hidden")}
function randLoading(){var list=["Montando sua retrospectiva 2025...","Relembrando os passos da sua empresa neste ano...","Organizando os destaques contábeis do ano..."];return list[Math.floor(Math.random()*list.length)]}
function incStat(slug){var raw=localStorage.getItem(statsKey);var obj=raw?JSON.parse(raw):{};obj[slug]=(obj[slug]||0)+1;localStorage.setItem(statsKey,JSON.stringify(obj))}
function makeGradient(c){var a=c;return "linear-gradient(135deg,"+a+" 0%,"+a+"33 50%,#0000 100%)"}
function slideEl(title,copy,brand,logo,kicker,imageUrl,footer,centerLogo){var d=document.createElement("div");d.className="slide";var s=document.createElement("div");s.className="sparkles";if(kicker){var k=document.createElement("div");k.className="kicker";k.textContent=kicker;d.appendChild(k)}var h=document.createElement("h2");h.className="title";h.innerHTML=title;var p=document.createElement("p");p.innerHTML=copy;d.appendChild(h);d.appendChild(p);if(imageUrl){var m=document.createElement("div");m.className="media";var orbs=document.createElement("div");orbs.className="orbs";for(var i=0;i<5;i++){var o=document.createElement("span");o.className="orb";var w=54+i*6;var hgt=18+i*4;o.style.width=w+"%";o.style.height=hgt+"%";o.style.left="50%";o.style.top=(20+i*9)+"%";o.style.transform="translateX(-50%)";o.style.backgroundImage="radial-gradient(ellipse at center,"+brand+" 0%, transparent 70%)";m.appendChild(o)}var pic=document.createElement("img");pic.src=imageUrl;m.appendChild(pic);d.appendChild(m)}if(footer){var f=document.createElement("div");f.className="footer";f.innerHTML=footer;d.appendChild(f)}if(logo&&centerLogo){var lg=document.createElement("img");lg.className="logo-center";lg.src=logo;d.appendChild(lg)}d.appendChild(s);return d}
function shareUrl(){if(location.hostname==="localhost")return location.origin+"/index.html#/"+state.slug;return location.origin+"/"+state.slug}
function buildSlides(){var name=state.visitorName||"Você";var comp=state.visitorCompany||"sua empresa";var brand=state.client?state.client.color:"#6a5acd";var logo=state.client?state.client.logo:null;var container=document.getElementById("slides");container.innerHTML="";var arr=[
  ["Olá <span class=\"accent\">"+name+"</span>, aqui é a <span class=\"accent\">"+(state.client?state.client.name:"Contabilidade XY")+"</span>","Temos uma mensagem muito especial pra você… passe para o lado.",null,null],
  ["2025 foi <span class=\"accent\">o ano</span>","2025 foi o ano da sua empresa "+(comp||"sua empresa")+" escrever mais um capítulo especial — e nós estivemos com você em cada linha dessa história.","Boas-vindas","https://dpvgtsmwsmtpdeuwhqun.supabase.co/storage/v1/object/public/imagens/retro01.webp",""],
  ["Cenário de <span class=\"accent\">Crescimento</span>","Sabia que o Brasil bateu recorde com mais de 3,8 milhões de novos pequenos negócios em 2025? O seu empreendimento fez parte dessa onda que não para de crescer.",null,"https://dpvgtsmwsmtpdeuwhqun.supabase.co/storage/v1/object/public/imagens/retro02.webp","A <span class=\"accent\">"+(comp||"sua empresa")+"</span> fez parte dessa onda."],
  ["Transformações <span class=\"accent\">Tributárias</span>","Foi o ano da Reforma Tributária. Novos impostos, novas regras. E você enfrentou tudo com coragem e apoio contábil.",null,"https://dpvgtsmwsmtpdeuwhqun.supabase.co/storage/v1/object/public/imagens/retro03.webp","<span class=\"accent\">"+name+"</span>, você enfrentou com coragem."],
  ["Digitalização e <span class=\"accent\">Eficiência</span>","2025 acelerou tudo: IA, automação, plataformas online. E a sua empresa não ficou pra trás.",null,"https://dpvgtsmwsmtpdeuwhqun.supabase.co/storage/v1/object/public/imagens/retro04.webp","E a <span class=\"accent\">"+(comp||"sua empresa")+"</span> não ficou pra trás."],
  ["Compliance e <span class=\"accent\">ESG</span>","Mais do que cumprir obrigações, muitas empresas decidiram fazer diferente. Você foi uma delas.",null,"https://dpvgtsmwsmtpdeuwhqun.supabase.co/storage/v1/object/public/imagens/retro05.webp","<span class=\"accent\">"+name+"</span>, você foi uma delas."],
  ["Gratidão e Reconhecimento","Obrigado por confiar em nós. Ver sua empresa prosperar é o que nos move.",null,null,null],
  ["Mensagem de Fechamento","2026 já está chegando. E com ele, novas chances de crescer — juntos.",null,null,null]
];var deck={index:0,slides:[]};for(var i=0;i<arr.length;i++){var item=arr[i];var centerLogo=i===0||i===arr.length-1;var el=slideEl(item[0],item[1],brand,logo,item[2],item[3],item[4],centerLogo);if(i===arr.length-1){var box=document.createElement("div");box.style.marginTop="12px";var w=document.createElement("a");w.className="primary";w.style.display="block";w.style.textAlign="center";w.style.marginBottom="8px";var msg=encodeURIComponent("Veja minha Retrospectiva 2025: "+shareUrl());w.href="https://wa.me/?text="+msg;w.target="_blank";w.textContent="Compartilhar no WhatsApp";var cp=document.createElement("button");cp.className="ghost";cp.textContent="Copiar link";cp.onclick=function(){navigator.clipboard.writeText(shareUrl())};box.appendChild(w);box.appendChild(cp);el.appendChild(box)}container.appendChild(el);deck.slides.push(el)}
  function setPositions(){for(var i=0;i<deck.slides.length;i++){var rel=i-deck.index;var el=deck.slides[i];var x=0;var s=1;var o=0;var pe="none";if(rel===0){x=0;s=1;o=1;pe="auto"}else if(rel===1){x=18;s=.98;o=.20}else if(rel===-1){x=-18;s=.98;o=.20}else{x=rel>0?36:-36;s=.96;o=0}el.style.opacity=o;el.style.pointerEvents=pe;el.style.transform="translateX(-50%) translateX("+x+"%) scale(calc(var(--scale,1) * "+s+"))";el.style.zIndex=""+(100-Math.abs(rel));el.classList.toggle("active",rel===0)}var atEnd=deck.index===deck.slides.length-1;if(atEnd&&!confettiFired){confettiFired=true;launchConfetti()}if(!atEnd){confettiFired=false}}
  function next(){deck.index=Math.min(deck.index+1,deck.slides.length-1);setPositions()}
  function prev(){deck.index=Math.max(deck.index-1,0);setPositions()}
  var activeEl=null,startX=0,deltaX=0,dragging=false;function px(e){return e.touches?e.touches[0].clientX:e.clientX}
  container.addEventListener("pointerdown",function(e){activeEl=deck.slides[deck.index];startX=px(e);deltaX=0;dragging=true;activeEl.style.transition="none"});
  window.addEventListener("pointermove",function(e){if(!dragging||!activeEl)return;deltaX=px(e)-startX;var percent=(deltaX/activeEl.clientWidth)*100;activeEl.style.transform="translateX(-50%) translateX("+percent+"%) scale(1)";activeEl.style.opacity=Math.max(.85,1-Math.abs(deltaX)/600)});
  window.addEventListener("pointerup",function(){if(!dragging)return;dragging=false;var threshold=60;if(deltaX<-threshold)next();else if(deltaX>threshold)prev();activeEl.style.transition="";setPositions();activeEl=null});
  var la=document.getElementById("leftArrow");var ra=document.getElementById("rightArrow");if(la)la.onclick=prev;if(ra)ra.onclick=next;setPositions()}
function init(){state.slug=getSlug();state.client=getClientBySlug(state.slug);if(state.client){setBrand(state.client.color);setLogo("")}else{setBrand("#6a5acd");setLogo("")}
  show("landing");var progressed=false;function goto(){if(progressed)return;progressed=true;try{incStat(state.slug);buildSlides()}catch(e){var s=document.getElementById("slides");if(s){s.innerHTML="<div class=\"slide\"><h2>Retrospectiva</h2><p>Modo básico carregado.</p></div>"}}show("retrospective")}
  document.getElementById("startBtn").addEventListener("click",function(){var n=document.getElementById("visitorName").value.trim();var c=document.getElementById("visitorCompany").value.trim();state.visitorName=n;state.visitorCompany=c;document.getElementById("loadingText").textContent="Verificando cliente...";show("loading");setTimeout(function(){document.getElementById("loadingText").textContent=randLoading()},800);setTimeout(goto,1800)});
  function updateScale(){var h=window.innerHeight*0.92/1350;var w=window.innerWidth*0.8/1080;var sc=Math.min(h,w);document.documentElement.style.setProperty('--scale',sc.toFixed(3))}
  updateScale();window.addEventListener('resize',updateScale);
}
function launchConfetti(){var el=document.getElementById('confetti');if(!el)return;el.classList.remove('hidden');el.innerHTML='';var canvas=document.createElement('canvas');el.appendChild(canvas);var ctx=canvas.getContext('2d');function size(){canvas.width=el.clientWidth*window.devicePixelRatio;canvas.height=el.clientHeight*window.devicePixelRatio}size();var parts=[];function burst(cx,cy,count){for(var i=0;i<count;i++){var ang=Math.random()*Math.PI*2;var sp=4+Math.random()*3;parts.push({x:cx,y:cy,vx:Math.cos(ang)*sp,vy:Math.sin(ang)*sp,life:60+Math.random()*40})}}var w=canvas.width,h=canvas.height;burst(w*0.5,h*0.5,80);burst(w*0.2,h*0.3,50);burst(w*0.8,h*0.4,50);var tick=0;function step(){ctx.clearRect(0,0,w,h);ctx.globalCompositeOperation='source-over';for(var i=0;i<parts.length;i++){var p=parts[i];p.vy+=0.06;p.x+=p.vx;p.y+=p.vy;p.life-=1;ctx.fillStyle='#f7d27a';ctx.beginPath();ctx.arc(p.x,p.y,3,0,6.283);ctx.fill()}tick++;if(tick<180&&parts.some(function(p){return p.life>0}))requestAnimationFrame(step);else{el.classList.add('hidden');el.innerHTML=''}}requestAnimationFrame(step)}
if(document.readyState!=="loading"){var t=localStorage.getItem(themeKey)||"light";applyTheme(t);var tg=document.getElementById("themeToggle");setToggleIcon(tg,t);if(tg){tg.onclick=function(){t=t==="dark"?"light":"dark";applyTheme(t);setToggleIcon(tg,t)}}init()}else{document.addEventListener("DOMContentLoaded",function(){var t=localStorage.getItem(themeKey)||"light";applyTheme(t);var tg=document.getElementById("themeToggle");setToggleIcon(tg,t);if(tg){tg.onclick=function(){t=t==="dark"?"light":"dark";applyTheme(t);setToggleIcon(tg,t)}}init()})}
